## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
arr = np.random.randint(-1, 10, 10)
arr

array([7, 6, 5, 0, 5, 3, 2, 4, 3, 1])

In [3]:
for i in range(arr.size):
    if arr[i] > 3 and arr[i] < 8:
        arr[i] -= arr[i]*2
arr

array([-7, -6, -5,  0, -5,  3,  2, -4,  3,  1])

**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
arr[arr == arr.max()] = 0
arr

array([-7, -6, -5,  0, -5,  0,  2, -4,  0,  1])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
def cartesian(arrays): # сам бы не догнал до такого
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 5]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
a =np.random.randint(2,size=10*3).reshape(10,3)
print(a)
a = a[(a[:,1]!=a[:,0]) | (a[:,2]!=a[:,0])]

[[0 0 1]
 [1 1 1]
 [0 1 1]
 [0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]
 [1 0 0]
 [1 0 0]
 [0 0 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
b = np.random.randint(1,4,(10,2))
uniques,idx = np.unique(b,axis=0,return_index=True)
print(f"output:\n{uniques[idx.argsort()]}")

output:
[[1 3]
 [2 1]
 [3 2]
 [1 1]
 [2 3]
 [3 3]
 [3 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [36]:
X = np.random.randint(0,4,(10,10))
result =1
for i in range(0,min(len(X),len(X[0]))):
    if(X[i][i]):
        result*=X[i][i]
    
print(X)
result

[[2 0 0 3 3 1 0 3 0 1]
 [2 0 1 3 2 1 2 2 1 3]
 [0 3 0 3 3 1 2 2 3 0]
 [2 1 2 3 1 0 3 3 0 2]
 [2 3 2 3 0 2 3 2 1 2]
 [2 1 1 1 3 2 3 0 0 3]
 [1 3 2 1 1 2 3 0 2 2]
 [1 3 2 3 2 2 0 3 3 0]
 [0 0 2 3 2 2 2 3 0 3]
 [0 1 0 2 2 0 1 0 1 0]]


108

In [9]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
d  = X.diagonal()
np.multiply.reduce( d[d!=0])

3

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [39]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
x.sort() == y.sort()

True

In [40]:
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
sorted(x)==sorted(y)

True

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [41]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
np.max(x[1:][(x==0)[:-1]])

5

In [42]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
max_element = min(x)
for i in range(1,len(x)):
    if x[i-1]==0 and x[i]>max_element:
        max_element = x[i]    
max_element

5

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [44]:
x = np.array([2, 2, 2, 3, 3, 3, 5])
np.unique(x,return_counts=True)

(array([2, 3, 5]), array([3, 3, 1]))

In [45]:
x = [2, 2, 2, 3, 3, 3, 5]
unique=[]
counts=[]
current = x[0]
current_amount = 1
for i in range(1,len(x)):
    if x[i]==current:
        current_amount+=1
    else:
        unique.append(current)
        counts.append(current_amount)
        current = x[i]
        current_amount = 1
unique.append(current)
counts.append(current_amount)    
(unique,counts)

([2, 3, 5], [3, 3, 1])

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [46]:
from timeit import default_timer
coords = [(35.0456, -85.2672),
          (35.1174, -89.9711),
          (35.9728, -83.9422),
          (36.1667, -86.7833)]
start = default_timer()
X = np.array(coords)
X1= np.repeat(X,4,axis=0).reshape(4,4,2)
Y = np.array(coords)
Y1= np.repeat(Y,4,axis=0).reshape(4,4,2).transpose(1,0,2)
A=np.square(X1-Y1)
print(np.sqrt(A.sum(axis=2)))
end = default_timer()
result1 = end-start
print(result1)

from scipy.spatial import distance
start = default_timer()
print(distance.cdist(coords, coords, 'euclidean'))
end = default_timer()
result2 = end-start
print(result2)
print(f"scipy is {result1-result2}ms faster")

[[0.         4.70444794 1.6171966  1.88558331]
 [4.70444794 0.         6.0892811  3.35605413]
 [1.6171966  6.0892811  0.         2.84770898]
 [1.88558331 3.35605413 2.84770898 0.        ]]
0.0012094190000198068
[[0.         4.70444794 1.6171966  1.88558331]
 [4.70444794 0.         6.0892811  3.35605413]
 [1.6171966  6.0892811  0.         2.84770898]
 [1.88558331 3.35605413 2.84770898 0.        ]]
0.01940819300000385
scipy is -0.01819877399998404ms faster


In [47]:
import math
from timeit import default_timer
coords = [(35.0456, -85.2672),
          (35.1174, -89.9711),
          (35.9728, -83.9422),
          (36.1667, -86.7833)]

start = default_timer()
X = coords
Y = coords
matrix = []
for x_row in X:
    for y_row in Y:
        matrix.append([])
        result = 0
        for i in range(0,len(x_row)):
            result+=pow(x_row[i]-y_row[i],2)
        matrix[len(matrix)-1].append(math.sqrt(result))
print(matrix)
end = default_timer()
result1 = end-start
print(result1)

from scipy.spatial import distance
start = default_timer()
print(distance.cdist(coords, coords, 'euclidean'))
end = default_timer()
result2 = end-start
print(result2)
print(f"scipy is {result1-result2}ms faster")

[[0.0], [4.704447943170383], [1.6171965990565296], [1.8855833102782755], [4.704447943170383], [0.0], [6.089281104531148], [3.3560541309698886], [1.6171965990565296], [6.089281104531148], [0.0], [2.8477089774062208], [1.8855833102782755], [3.3560541309698886], [2.8477089774062208], [0.0]]
0.0014180590000023585
[[0.         4.70444794 1.6171966  1.88558331]
 [4.70444794 0.         6.0892811  3.35605413]
 [1.6171966  6.0892811  0.         2.84770898]
 [1.88558331 3.35605413 2.84770898 0.        ]]
0.0009312859999681677
scipy is 0.00048677300003419077ms faster


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [14]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [15]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [16]:
average_calories = np.mean(calorie_stats) - 60
average_calories

46.883116883116884

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [17]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [18]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [48]:
nth_procentile = 0
while np.percentile(calorie_stats,nth_procentile)<=60:
    print(np.percentile(calorie_stats,nth_procentile))
    nth_procentile+=1
nth_procentile

50.0
50.0
50.0
55.599999999999994


4

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [20]:
more_calories = len(calorie_stats[calorie_stats>60])/len(calorie_stats)*100
more_calories

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [21]:
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [49]:
#более 96% хлопьев содержат больше калорий, чем наши. Наши хлопья в среднем более чем на три стандартных отклонения круче,
#чем хлопья конкурентов. Мы красавчики. В среднем, любые другие хлопья содержат на 75% больше калорий, чем наши. Но все это неважно.
#Ведь единственное, что остается после хлопьев конкурентов, это вечера, полные грусти, грусти, которую чувствует человек, ибо
#все на земле преходяще, а он — единственное существо на земле, которое это знает, как знает и то,
#что в этом — наше утешение. Хотя и не понимает почему. Хлопья CrunchieMunchies - балдеж. 